---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: postgres_password
  namespace: recipes
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres_password
  namespace: recipes
spec:
  refreshInterval: "30m"
  target:
    name: postgres_password
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: postgres_password
