---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-dmz
  namespace: kube-system
spec:
  config: |
    {
      "cniVersion": "1.1.0",
      "name": "multus-dmz",
      "plugins": [
        {
          "type": "macvlan",
          "master": "enp86s0",
          "mode": "bridge",
          "ipam": {
            "type": "host-local",
            "ranges": [
              [
                {
                  "subnet": "10.0.4.0/24",
                  "rangeStart": "10.0.4.240",
                  "rangeEnd": "10.0.4.250"
                }
              ]
            ],
            "routes": [
              {
                "dst": "10.0.4.0/24"
              }
            ]
          }
        }
      ]
    }
