---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot
  namespace: kube-system
spec:
  config: |
    {
      "cniVersion": "1.1.0",
      "name": "multus-iot",
      "plugins": [
        {
          "type": "macvlan",
          "master": "enp86s0.500",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "10.0.5.1/24", "gw": "10.0.5.1" }
            ]
          }
        }
      ]
    }
