---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: chat
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: bjw-s
  values:
    controllers:
      chat:
        containers:
          web:
            image:
              repository: ghcr.io/cinnyapp/cinny
              tag: v3.2.0
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      chat:
        type: LoadBalancer
        controller: chat
        ports:
          http:
            port: 80
    ingress:
      chat:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt"
        hosts:
          - host: chat.cjf.sh
            paths:
              - path: /
                service:
                  identifier: chat
                  port: http
        tls:
          - hosts:
              - chat.cjf.sh
            secretName: chat-ingress-cert
