---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bjw-s
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./k8s/apps/bjw-s
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: bjw-s
  timeout: 3m0s
  wait: true
