---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metallb
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      version: 0.14.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: metallb
  values:
    prometheus:
      serviceAccount: prometheus-operator
      podMonitor:
        enabled: true
      prometheusRule:
        enabled: true
