---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: acme@cjf.sh
    server: https://acme-staging-v02.api.letsencrypt.org/directory
  solvers:
    - selector:
      dnsZones:
        - "cjf.sh"
      dns01:
        route53:
          region: us-east-1
          accessKeyIDSecretRef:
            name: prod-route53-credentials
            key: access-key-id
          secretAccessKeySecretRef:
            name: prod-route53-credentials
            key: secret-access-key
