---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mqtt
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: mqtt
    namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: hass
  valuesFrom:
    - kind: ConfigMap
      name: mqtt-config-values
