---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wakeword
  namespace: flux-system
spec:
  chart:
    spec:
      chart: app-template
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: hass
  values:
    global:
      fullnameOverride: wakeword
    controllers:
      wakeword:
        containers:
          app:
            image:
              repository: docker.io/rhasspy/wyoming-openwakeword
              tag: "1.10.0"
            args:
              - --custom-model-dir
              - /custom
    service:
      app:
        controller: wakeword
        ports:
          http:
            port: 10400
    persistence:
      data:
        type: emptyDir
        globalMounts:
          - path: /data
            readOnly: false
      custom:
        type: hostPath
        hostPath: /srv/custom
        hostPathType: DirectoryOrCreate
        globalMounts:
          - readOnly: true
