---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cnpg
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
      version: 0.26.x
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: cnpg
  valuesFrom:
  - kind: ConfigMap
    name: cnpg-config-values
