---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mqtt
  namespace: flux-system
spec:
  chart:
    spec:
      chart: emqx
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
      version: 5.8.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: hass
  values:
    fullnameOverride: mqtt
    metrics:
      enable: true
    persistence:
      enabled: true
      storageClassName: openebs-hostpath
      accessMode: ReadWriteOnce
      size: 100Mi
    ingress:
      mqtt:
        enabled: true
        ingressClassName: nginx
        hosts:
          - mqtt.cjf.sh
        tls:
          - hosts:
              - mqtt.cjf.sh
