---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: blocky
    namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: blocky
  valuesFrom:
  - kind: ConfigMap
    name: blocky-config-values
