---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: blocky
    namespace: flux-system
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: blocky
  dependsOn:
    - name: blocky-redis
