---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: flux-system
spec:
  chart:
    spec:
      chart: app-template
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: blocky
  values:
    global:
      fullnameOverride: blocky
    controllers:
      blocky:
        replicas: 3
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/0xerr0r/blocky
              tag: "v0.25"
    service:
      app:
        controller: blocky
        ports:
          http:
            port: 80
          init:
            port: 3000
      dns:
        controller: blocky
        type: LoadBalancer
        ports:
          dns-udp:
            port: 53
            protocol: UDP
          dns-tcp:
            port: 53
    persistence:
      config:
        name: blocky-config
        type: configMap
        advancedMounts:
          blocky:
            app:
              - path: /app/config.yml
                subPath: config.yml
    configMaps:
      config:
        data:
          config.yml: |
            upstreams:
              groups:
                default:
                  - https://dns.cloudflare.com/dns-query
            bootstrapDns:
              - https://1.1.1.1/dns-query
              - https://1.0.0.1/dns-query
            blocking:
              denylists:
                ads:
                  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
                meta:
                  - https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/share/facebook.txt
              clientGroupsBlock:
                default:
                  - ads
                  - meta
            ports:
              dns: 53
              http: 4000
            prometheus:
              enable: true
            redis:
              address: redis-primary.blocky:6379
              required: true
            log:
              level: info
              format: json
