---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: flux-system
spec:
  chart:
    spec:
      chart: app-template
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: blocky
  values:
    controllers:
      blocky:
        containers:
          app:
            image:
              repository: ghcr.io/0xerr0r/blocky
              tag: "v0.25"
    service:
      app:
        controller: blocky
        ports:
          http:
            port: 80
          init:
            port: 3000
      dns:
        controller: blocky
        type: LoadBalancer
        ports:
          dns-udp:
            port: 53
            protocol: UDP
          dns-tcp:
            port: 53
    persistence:
      config:
        name: blocky-configmap
        type: configMap
        advancedMounts:
          blocky:
            app:
              - path: /app/config.yml
                subPath: config.yml
    configMaps:
      config:
        data:
          foo: bar
