---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blocky
  namespace: blocky
spec:
  selector:
    matchLabels:
      app.kubernetes.io/service: blocky-app
  namespaceSelector:
    matchNames:
      - blocky
  endpoints:
    - port: http
      interval: 30s
