apiVersion: v1
kind: Secret
metadata:
  name: tududi
  namespace: tududi
stringData:
  OIDC_ENABLED: ENC[AES256_GCM,data:nHZxrQ==,iv:moehD8DECfdYqj7GbTU/jlHFgPDJafXXz5ikZRYCsCc=,tag:T+8mfxBSoeYF7Op74fIL/Q==,type:str]
  OIDC_PROVIDER_NAME: ENC[AES256_GCM,data:pGhXgLI8nxM=,iv:+Fa0GIzC8g2/p3GgCZ0ZJWnyH53agddXSUiJEu21lCg=,tag:5KURJgHTDuaomnJ/2rhRIg==,type:str]
  OIDC_PROVIDER_SLUG: ENC[AES256_GCM,data:DoVEuQl18V4=,iv:QO0UyNgvKebFuk7eR7X2iooAIsBJXC2leDDxbXw7ofo=,tag:QZAsXg+zUyVcXrqp8MyxEQ==,type:str]
  OIDC_ISSUER_URL: ENC[AES256_GCM,data:oTLUwj6LCoRLabp0BJaiyT/6Cw==,iv:NvruY8bAg1PATH165aEFhWXp2dNIRPp1dL7BqD9hy7o=,tag:qZ/KG0ykWXm86BXUdkjGoA==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:BHIHagMPpe3KfuZTrxtmiDb9Gd19fXNIdnTU4h0QwMivLWP4,iv:3a39b4jxwEkZiy9r/SxtwJ+hnkO00ZQQkyZdzq2xpEw=,tag:PFlIhVAz0ccQKZc2P73irA==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:+117eeWW1uvKpXMbdUyKQ/22tCp6EZFoDWgZeHYFsQU=,iv:VDbmjfCr/l2t6Qj6vXscWCf+ehED8NdpMEvznL0bfK4=,tag:pFH7qC/tWzuRRMHnSnOmVw==,type:str]
  OIDC_SCOPE: ENC[AES256_GCM,data:0U9qptGA0H5G/CPVnFSiptBR2kI=,iv:J1n0NIw96VF+cArJVzqmjkQedvWzXHLHksIyDrObvGI=,tag:wyirR6nPDlNFdE8WLqtROw==,type:str]
  OIDC_AUTO_PROVISION: ENC[AES256_GCM,data:iu7SqA==,iv:SiLuXSYkE61T/RAR7RZ4tEVJcWoUqvmHTa3a2kgDAxc=,tag:6aCDFBgC2Ks3PnfRSdmCEg==,type:str]
sops:
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ck5hMDhITmZvMkJXN2dV
        QlpzV09ZQ2Izd20wbkZSV3ZDY2dMWThZaXg0Cnd1TnZVcWFPT09ob2lxdGxUNkcx
        ZG1hWWtjYXR2eUNGU1B5c243ekxOczgKLS0tIEo3UUFHN2dVUFpkeVJBWXVaOE8r
        QnBwQlpQdTZBV2NWdFQ1WmpWWjhsUUEKo1mLc+ISNnMkgMdyiNXO61UhfqM3nHE3
        Vi9hbAJu0hLKytvE91KmjKUe6yLqRrKk+IqofHNkksCzgRnthSby/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T02:12:14Z"
  mac: ENC[AES256_GCM,data:RMfZAeEYwXsWYkVmZjIQAL8pgmYYwnUczD0uZodgFJeygZOfF2hTt0JCyEpiPNW9J02aeoUNdfR0cmf8AytA4kAH3V0xbkQNgqWbjBfk6HMuz6G0H9qcOj49itB5Ga6Wgtn9+KQ9AC/mQ/6WWScncL3oRIRAAVkxEZUK3DghS8c=,iv:itRFi9JseM+TkY5Xx2gP3CvR2aaEw5iwfpk3IhNzryA=,tag:QyREMgAX0XnchavpkIjvVQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.0
