apiVersion: v1
kind: Secret
metadata:
  name: tududi
  namespace: tududi
stringData:
  OIDC_ENABLED: ENC[AES256_GCM,data:7X4WOg==,iv:SSXclYcu++ziTkk47slweC45sMl18C9b/r1QoSkcesc=,tag:sIm2C4eng/UypHAznpnqtQ==,type:bool]
  OIDC_PROVIDER_NAME: ENC[AES256_GCM,data:Cfo7ebMsPU4=,iv:Bdes1QqJUscte0ZY6ForH/GjlHOmFBj8sDazOGDd3M8=,tag:bv3AgsYgqm+XX4i0ztr/uw==,type:str]
  OIDC_PROVIDER_SLUG: ENC[AES256_GCM,data:LXGUp/tI/vM=,iv:nH93VY5vAYvpUA65RVrxtLkD/as4jJFaLM96nnq7pLA=,tag:zg9tGsrEhPATyocEPqAEKQ==,type:str]
  OIDC_ISSUER_URL: ENC[AES256_GCM,data:LaOHtzNQ6jyRNeMkQ/QG74rsXw==,iv:nsRt5k4GPtp4MCeU+q1EDmJa1SPz8jK6OgTI5fSf8Jg=,tag:oZaeHrljoCMby2R22kJkJw==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:1W4d4wT987FystE2b8soUmGeVkwiO/bSMTIWJjREdJtVS87q,iv:Ml2+jgCPDrpSxTcEDSa4usiyCRi/6lfw999nwcjrPJI=,tag:tb0/Ci/26u5hm207eCKtUg==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:VxaSfJ7mtlWSTBqoObgrrLOD5d5F3JwIYypaI9dIL7k=,iv:0rnnRLifOvsEjlOCUxwogI0UVxQkrLZvqNJLw6I4Sk8=,tag:3oIcIyRwaG4cV6nVvNsftQ==,type:str]
  OIDC_SCOPE: ENC[AES256_GCM,data:OJJZQKYXO2gqjVqRv1+RWN7TApk=,iv:FcDv5+2zkSxzyRm5WlXI4wHwFoEh35SYCbYyL4PMf4I=,tag:E/S/tfiI/PfT5boPnUyQ1A==,type:str]
  OIDC_AUTO_PROVISION: ENC[AES256_GCM,data:XY7G7g==,iv:LcGwfsY9UopAkG2cOpoQJnlCcF3yt2sUM/oSIWkG1sM=,tag:0+G7qALqgc8UUJLMKLxkvg==,type:bool]
sops:
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUR01UT1JPZldhZlhTTXhT
        NnFrMVVQQmhHbklSUWptUnk4K0NrU3RiSjJnClBPWUZIUWhZK3JWUE5OYVVTRDBL
        QjBYUzloYVhiRTdMV0V4NDJTbEwvR2sKLS0tIHk3WGE5SDJsM0sxUG0yTHA3ZTRN
        T3QycVBHMTZuc3NLNENjdHRlYXFXa2MKxJ4j/5OOVChxWyvGjh/dD04sWuyNjb9J
        L+MDh6HWBeUsQgEhP93laPc+ss/gwaN1QLb+kI6ZABySTrTfBtfmJQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T01:58:55Z"
  mac: ENC[AES256_GCM,data:ieRKf7Hte8pXPf36TMis1VpbWYpVT+wjc+hWNUTwHc3ko/SXZyhqIYo2k86B/+g0EccryaRID/Th847fZpo+8ospNuMkHdSSV++0ZGNtXAxZ7MDRt1SbC4bttBBBYhTvqQklaOKmOkNT7/4exgsPHRDZtK0gH9WJZB8fyCKFMTo=,iv:ZdM3JBxmCy8EkGikRxjwain8xrQYC4GdCJG5hMdiuk8=,tag:0usgXNeraYYDUD85a34GrA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.0
