apiVersion: v1
kind: Secret
metadata:
  name: tududi
  namespace: tududi
stringData:
  TUDUDI_USER_EMAIL: ENC[AES256_GCM,data:nlTbeFE6fTneLH8p,iv:dla9x+p0q6J0neIUqnS0qayMjRsdMAsy64m5gJ6rZ2I=,tag:od+B76q5ZFws+yL/FZRGsA==,type:str]
  TUDUDI_USER_PASSWORD: ENC[AES256_GCM,data:irmmkYWp8+hnW0kIhwUYCb1QmkPDakigkxcrahSqspdOIRtHJN00SoQdEQ8iuaHmQLL7x0Ly8bkXdTai8t3imQ==,iv:e5Ji23YhoXiKbNehpvf1a/71kUI7GbbhNdUBlRriVdE=,tag:LoG9lpWUvGEhcBXImoS40Q==,type:str]
  TUDUDI_SESSION_SECRET: ENC[AES256_GCM,data:CMkiwKsuAnNdZ9BdbILafbbz4Va6lRVPtOTrHoUJSwnyD7Noy5/H7tpwfD7dgFeuXpWelDlvUUjjYDEl9s8Urw7+GYi7XcXzz7n9hySo4yOVt7BfZNJo3wGiuCTD2AIbFYXaBQrTQpkU5cN4hFrEExXa1pvgyq8EHiLTmqvQLiY=,iv:FnXZs5mkk8RANUjoqaYVU2ynMNcofxXYIOamJw7yw0c=,tag:BnO9SIJ5kDbxEH3rW5AAFA==,type:str]
  TUDUDI_TRUST_PROXY: ENC[AES256_GCM,data:/MQdSg==,iv:jFdkXZatq4gRtcdw4FV2GnW7uZiJ+fZVfGj1eGXyYbI=,tag:kY9g1SbEu9i9EJ+jV4cVWA==,type:str]
  PASSWORD_AUTH_ENABLED: ENC[AES256_GCM,data:TgC/NA==,iv:Xed5lPpPerEhKuk+Kr12WZqUnJj0xAQjKrpHuPKjed4=,tag:feCBoYn0R5Sj0upqC79S9A==,type:str]
  OIDC_ENABLED: ENC[AES256_GCM,data:vQL5ZQ==,iv:OmxpIvY77NQNKXfTZaoJaeydLjDDej8w+gpvut75ylE=,tag:JPKIVXLz/WkvB9vjnldykA==,type:str]
  OIDC_PROVIDER_NAME: ENC[AES256_GCM,data:NBBOmvdAceg=,iv:sveakBy4iJ0M9IQg0X7u9kHszdOdf0zulRIxQg5WYdE=,tag:JY1IGod5nwk/9oroA2eyZw==,type:str]
  OIDC_PROVIDER_SLUG: ENC[AES256_GCM,data:hlFjuSjRCtA=,iv:2dGOflb3e9Ku2O0QZFWiNxyERQDilc3zkcQDVMwoj24=,tag:xwYeFWvsE99EMg72N7XQ3g==,type:str]
  OIDC_ISSUER_URL: ENC[AES256_GCM,data:IciuWDHKi5Kird4CsNiptp7A7w==,iv:Znuwj1Sy0w9zP64qLeAtr1GZuDEGFWCFwQlfRQrM82s=,tag:LKmRR0X3gQhsVNJn/RGvdA==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:RhHAz6m3jCE/QWlrPD+3UTmQ4P08vw6cBky+7XrhnZR0sJfK,iv:9wVjmCr8SZ7I7jVKKGYa7gDBnsWDVD+QBWkeoUMO4Qo=,tag:cYI7szhvOBSNTyfslN5VTA==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:B/fg4Siyq9Dm6MbVXRPx0ehms91XLmMQ4YZUwm9EF9g=,iv:l3J2FT2V+B3rlpp7UgwejjczCp7XJRa9EiQ5VzRIQC0=,tag:r7eQ0o5Gp18Rm+P8Nih9zA==,type:str]
  OIDC_SCOPE: ENC[AES256_GCM,data:/rvsMnPTl6Vll+wkdz1TG7lxSfY=,iv:XJKAQDfO2rbrFzr1q6bGS4plkV4wS9+o0e9kOzWwGYE=,tag:0HP3MHFw9m3Rv3pcIKEQ0g==,type:str]
  OIDC_AUTO_PROVISION: ENC[AES256_GCM,data:Br2rZA==,iv:f9J3w5OktrJYyTDQeCQunPP6/ukiE3kXrTVIr2nvtHk=,tag:7kga2+vcDFO5zfc49AD94g==,type:str]
sops:
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArL3dZeGhLTmtqVDcrc3ht
        WGFnbW9iN3EvSDdjUHM3S29TZUJDLythVFdzCkFRU3dMdmp2RjczaUl2K01SalU0
        RzFjdzkyVm9PWTRuSzdGSFFKZ0VBU0kKLS0tIEt0d3JLRlI3VzdpWW82OUhJL29q
        Wm8wU1U5eXM2akJHdVdRbkNicTNFNGMKk164Z8a5tR7vJk3sRfFks61u87R8Zjoh
        YgpvBxv+mnZet56s3aafD7k7ufpGcY5yTCJD01kM45GnKhzJHxi/0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T02:37:41Z"
  mac: ENC[AES256_GCM,data:X2BCA7E1oVljLQUWh2Vnzg/DpI52GmjvaiZs7Ga/fgzMsOnKZn/bzeZLOH0kId/477EKtT1mGqblHoU/gbcHhiDcQoeJe8d1n5kpIAqIJjj2q3TRCfF3oFUMfRH17rWG1MIsXfvdfXi8YbVYjpPioBC5wlQUNCC9ABBZFYcIWCE=,iv:u9r8om4vONODzOrKdVLsBQSD7Hmfys/g1m5gftpKb+A=,tag:7DTYl99VrF6z8FL2naawsA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.0
