---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      version: 0.20.x
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: external-secrets
  valuesFrom:
  - kind: ConfigMap
    name: external-secrets-config-values
