---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: psmdb-operator
  namespace: flux-system
spec:
  interval: 10m0s
  provider: generic
  ref:
    tag: 1.21.2
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
