---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: 1.17.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: cert-manager
  dependsOn:
    - name: kube-prometheus-stack
  values:
    fullnameOverride: cert-manager
    crds:
      enabled: true
    dns01RecursiveNameservers: |-
      https://1.1.1.1:443/dns-query,https://1.0.0.1:443/dns-query
    dns01RecursiveNameserversOnly: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
