---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      version: 1.19.x
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: cert-manager
  valuesFrom:
  - kind: ConfigMap
    name: cert-manager-config-values
