---
apiVersion: ENC[AES256_GCM,data:izY=,iv:ZOWoYdBOyP1dWGM2rseXBNV3ilwYD0Cy17svacXCY8Q=,tag:eR7Z94qnl905ER2dFakjDg==,type:str]
data:
  access-key-id: ENC[AES256_GCM,data:g0lwnaiMLlpgnZ3/lu2v5DJUNmqLwiDdUT/1xQ==,iv:JSz021zGYQ1urpQmZ0Wo+jF676DvZgPpftVLHvPupo4=,tag:IEbD0Nu6G9tqNxVmxDxQBQ==,type:str]
  secret-access-key: ENC[AES256_GCM,data:3Xvq3vSqjHYZU2hap79R4pWx6shZ8y6cTAorbmp69vT4lclrSHQNSf0jW96LOhaL84FaAa5KpY8=,iv:9LS/Cbgm4w++gFCY17BpixakDNJLLRjIMht1puB4PyU=,tag:oYuK/GMLMDibxtysMQq5xw==,type:str]
kind: ENC[AES256_GCM,data:yak9nqni,iv:93bjnIDPVfRcMtpwM27yMyVGiepV+jBYMP5D12mYWQg=,tag:iYOqIDq+zVxMs+BA5/Y/WQ==,type:str]
metadata:
  creationTimestamp: null
  name: ENC[AES256_GCM,data:RAITipYWtejestfWLkJbLPqJcHPVKVxt,iv:R9DgE5EAqGOCBHWwE4QZBOTQie1GI8Tbw4/XlVtxIx4=,tag:m7Ozu4HndylDwLvtcHgUUw==,type:str]
  namespace: default
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaEU0M0tkdlc4Y1NmaTZW
        aDlCNUw2ZGRGWmtySm9yVnVnMjFEVFcyMkZZCnRkazVxMkJxZXU2QjRsc0JWUy85
        emkzQjZQVmxscWUzLzgvM1UxYkVNMXcKLS0tIHQ3eE5QTDZveVh6VHQzcjBYUUdr
        cU5HcWN3K1BqVkQ1VXY3U3VJUFZGNkUKdr1Vlkh6PWEvPsv4Uje3JodYKQckbfZU
        r207xYsoObR9v29DLGbJGBuv1roQP27VUbOOiFa7yn1R1exiDc2ePg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-29T23:55:58Z"
  mac: ENC[AES256_GCM,data:H2GqcyQhh59LLyG8c3fDE2JLKekzyXXBBaoEDyvBLLIlAMAbYP14upBjpzU9IzFUAeD21OUha3sFL3a40sqWuaDIJ6NKIwwG9gAbH7mvl6CW3JeJt4ojaeTxkpmQcRSByoY6MqTeye5nDBykrVf4RM9sOZq6CGgyHX6bVwox90g=,iv:UxwaDofuhXvYolflBbuhHECcMARNKoQYJLcQwI8gmzk=,tag:+SS5SO9ebn/RT8zwXlnhpA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.4
