---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir-distributed
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mimir-distributed
      version: "6.0.x"
      sourceRef:
        kind: HelmRepository
        name: mimir-distributed
        namespace: monitoring
      interval: 12h
  dependsOn:
    - name: kube-prometheus-stack
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: monitoring
  valuesFrom:
    - kind: ConfigMap
      name: mimir-distributed-config-values
