---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: hass-db
  namespace: hass
spec:
  instances: 3
  managed:
    roles:
      - name: hass
        login: true
  bootstrap:
    initdb:
      database: hass
      encoding: utf8
      owner: hass
      secret:
        name: hass-db
  storage:
    size: 4Gi
    storageClass: zfs-dataset
