---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: hass-db
  namespace: hass
spec:
  length: 42
  digits: 5
  symbols: 5
  symbolCharacters: "-_$@"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hass-db
  namespace: hass
spec:
  refreshInterval: "1h"
  target:
    name: hass-db
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: hass-db
