---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: flux-system
spec:
  chart:
    spec:
      chart: app-template
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: audiobookshelf
  values:
    global:
      fullnameOverride: audiobookshelf
    controllers:
      abs:
        type: statefulset
        containers:
          app:
            image:
              repository: ghcr.io/advplyr/audiobookshelf
              tag: 2.20.0

    service:
      app:
        controller: abs
        ports:
          http:
            port: 80

    ingress:
      app: &ingress
        enabled: true
        className: nginx
        hosts:
          - host: abs.cjf.sh
            paths:
              - path: /
                service:
                  identifier: app
                  port: mqtt
        tls:
          - hosts:
              - abs.cjf.sh

      tailscale:
        <<: *ingress
        className: tailscale

    persistence:
      config: &p
        type: persistentVolumeClaim
        storageClass: zfs-dataset
        globalMounts:
          abs:
            app:
              - path: /config
      audiobooks:
        <<: *p
        globalMounts:
          abs:
            app:
              - path: /audiobooks
      podcasts:
        <<: *p
        globalMounts:
          abs:
            app:
              - path: /podcasts
      metadata:
        <<: *p
        globalMounts:
          abs:
            app:
              - path: /metadata
