---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: chat
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./clusters/prod/chat
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: chat
  timeout: 3m0s
  wait: true
