---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/metallb
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 2m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-pool
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
  interval: 5m0s
  path: ./apps/metallb-pool
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 2m0s
  wait: true
  patches:
    - target:
        kind: IPAddressPool
        name: metallb
      patch: |
        - op: add
          path: /spec/addresses
          value:
            - 10.0.0.200-10.0.0.250
