---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: multus-attachments
  namespace: flux-system
spec:
  dependsOn:
  - name: multus
  interval: 5m0s
  path: ./apps/multus-attachments
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 2m0s
  wait: true
