---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: omada
  namespace: flux-system
spec:
  dependsOn:
    - name: storageclasses
    - name: ingress-nginx
    - name: tailscale
  interval: 5m0s
  path: ./apps/omada-controller
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m0s
  wait: true
