---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/openebs
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 2m0s
  wait: true
  patches:
    - patch: |
        - op: add
          path: /spec/values/localpv-provisioner/hostpathClass/basePath
          value:
            basePath: /var/tank
