---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pinchflat
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: pinchflat
    namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  storageNamespace: pinchflat
  targetNamespace: pinchflat
  valuesFrom:
  - kind: ConfigMap
    name: pinchflat-config-values
