apiVersion: v1
kind: Secret
metadata:
  name: actual-budget
  namespace: actual-budget
stringData:
  ACTUAL_OPENID_DISCOVERY_URL: ENC[AES256_GCM,data:rUxBq3dXImUpV9Q8sITBpqZyl3LXQvQTiLAFWUrjuaZzEDyHUw74cH6Q+BZN+qj2JlIQ3g==,iv:Bggd5FqpswX0xqCiwPl/5TRAhoImEjG6OgF0qwzn0oc=,tag:ZAilpkU1RlJdRBrujZNSZA==,type:str]
  ACTUAL_OPENID_CLIENT_ID: ENC[AES256_GCM,data:u1XZc+YrjrOnWdRiX5emVyZHcgi/vaDjaxZIrznuTQWsPLkb,iv:4aMy56kGk3fiFCaJmtrnWJtLh7Ojt3Tb12jFU0k8M8s=,tag:PFYXTqj+8JRex7nxq6OBOw==,type:str]
  ACTUAL_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:uVNwgQcWnhO0GI+P/w3kXKuQOWqPJa8hf2ztYkOx6fU=,iv:0TPW02YANMCL52e477ialKUUHYcw8IKr8hMtFIHaslU=,tag:WI5Iz780MCb6bYLrBLfS6w==,type:str]
  ACTUAL_OPENID_SERVER_HOSTNAME: ENC[AES256_GCM,data:XK39ER+hbOcaC7aac/k2IDwDsjM=,iv:vRNMiomaBlGbhNNO+mq5Ot2EYz6NieJCOkM+XhwedzY=,tag:xikwpYfUvudowXmnjzTijQ==,type:str]
sops:
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCU2xMNThaOHRwMDNWdGZQ
        ZTFNMGtwcUpCMmd6WUxhWEFkUUREZm5qeFM4ClVBQlVRUmsyb0Q5S0tXeHFTSGRr
        STRwZElaMVhadHB3UUZhb2hhQlgrTE0KLS0tIFBNaEoycit4NGNQSm1YOEVhajZv
        WWdwRVFJQkxCcng5QWUxWmZsZXlWblkK++7R2ex5t+CzG5Mrv1yoXA1IHdmcm8cc
        8qwGC/raoSH2q6upzywSkKv6baPHLZWjikAKI3UAzJHkTAZb/ueGHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T18:04:43Z"
  mac: ENC[AES256_GCM,data:In9Yrex50hcoA+n6M5fxDXTj6m7skGM5exRbH8PLjQD0NPgGUrS6jsiAHDzeObWZugMRwUTtcqUa4sC7U4gl041XdKi2v4mbYfUysuPUniwta1IgyHvZiyLgrFGIQrvB0I0EE/otjRsL1m/MO7arz6kg5l7z70BxT0wbhy8uSEE=,iv:BREznarcA/BjWIIXVAvGinWvCASxk0wCPCis9TUniCA=,tag:k2JwNRJQsFjUYVXqo2ibTw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
