apiVersion: v1
kind: Secret
metadata:
  name: actual-budget
  namespace: actual-budget
stringData:
  ACTUAL_OPENID_DISCOVERY_URL: ENC[AES256_GCM,data:TQ9JrJGtb7Lh8lF1PdvsBKtjsgnqHLzxP9h9vUAoB4/IAeK97CPO6NVkvxYxSHaw0c4RwQ==,iv:1qcZ+/+ZyjGDRx0nQWl3R6/thITjrDSwVD8/KSikZmw=,tag:DsLznVuHByHwTTF0A39SBA==,type:str]
  ACTUAL_OPENID_CLIENT_ID: ENC[AES256_GCM,data:Z3MLZWukFA4x2o2nXVOrd/juMCrPanxiW5TbNmDkZ3eSIvOr,iv:l9Pay475x8K/aFqp/fVsgO7/hUDOYktMiKMasyDBm0U=,tag:eb2l6z5v6v96J9PjgXSyNQ==,type:str]
  ACTUAL_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:FNnS0Wlz9uF9/1pulnRq6u1Y/H0BNLF4v0dRFFX/FJU=,iv:24sRU1UAffd7kIK2Of28Lczvks40AWsAZDSKQW+bTGk=,tag:SK2x8nM/+gYMxEZN5tw8bQ==,type:str]
  ACTUAL_OPENID_SERVER_HOSTNAME: ENC[AES256_GCM,data:IfWj7xWqzf3g07/4VWBZ5n4Xsek=,iv:tItwwe1gw957rTZdCaSCICFB97x0N1XejyGFpxFuLls=,tag:hHkNFNY8YQJI8KNmGIbjhw==,type:str]
  ACTUAL_OPENID_ENFORCE: ENC[AES256_GCM,data:aGx15w==,iv:uZltJk2sakNcY+phr4sCMIT19CntIaX/lM1jHWkDjIA=,tag:KZzEA/Nnl2q5XyL5azHueQ==,type:bool]
sops:
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OU5Gd2JEMFFRTzF5T3pV
        WjNtREFJOWZqd0l5WTQ4TFNFdG82RUdqQ0JVClRSQnNjcFVLQUdhbjdoVDE2bE1F
        cVJRVWx6bmRKRHBnYnRUUE9QZ0JMVjQKLS0tIGdZcGNuWExKOFN3UkduNUViWkJm
        anZvaVdDMitVRUVEWkNGTTczY3l4aUUKDPDXGVyWtVXqKxjlVb16sLnqxIVA+/14
        1G71d6UaA1Py0tf7y2LeGvfmM1BglBpjkXy5LsQm/I4D+lNpTp43gQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T18:06:59Z"
  mac: ENC[AES256_GCM,data:GlGkKosnzxUGeslPZqL41fzOEjlOmn9gQIaUWYgPDESydnd/UrWKox2tyHN/xP02pjMht/7CPt45X2yLS3fEknnP82l7rjmgp4ookU6HbLXcL1jOolreSImiwQkQIMWeMI9HzlD2B25bqEuwWi4VMgEyOwF5BTcnWR3FY8y1l8U=,iv:o9RQ+MAJ3zxPMUiw8tBEbBmWXpown9O7YkQX+ykzk/I=,tag:B0h+sYi/AXJ7cUM1TmpSKQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
