---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cinny
  namespace: flux-system
spec:
  chart:
    spec:
      chart: app-template
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: cinny
  values:
    global:
      fullnameOverride: cinny
    controllers:
      chat:
        containers:
          app:
            image:
              repository: ghcr.io/cinnyapp/cinny
              tag: v4.6.0
    service:
      app:
        controller: chat
        type: LoadBalancer
        ports:
          http:
            port: 80
    ingress:
      app: &ingress
        className: nginx
        hosts: &hosts
          - host: chat.cjf.sh
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - chat.cjf.sh
      tailscale:
        <<: *ingress
        className: tailscale
