---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: flux-system
spec:
  chart:
    spec:
      chart: node-feature-discovery
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
      version: 0.17.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: node-feature-discovery
  dependsOn:
    - name: kube-prometheus-stack
  values:
    prometheus:
      enable: true
