---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emqx-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: emqx-operator
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
      version: 2.2.x
  interval: 30m0s
  dependsOn:
    - name: cert-manager
