---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gpu-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
      version: v25.10.0
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: nvidia
  valuesFrom:
    - kind: ConfigMap
      name: nvidia-config-values
