---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: smartctl-exporter
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: smartctl-exporter
    namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: monitoring
  valuesFrom:
    - kind: ConfigMap
      name: smartctl-exporter-config-values
