---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-smartctl-exporter
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
  chart:
    spec:
      chart: prometheus-smartctl-exporter
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 0.13.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: monitoring
  values:
    fullnameOverride: smartctl-exporter
    serviceMonitor:
      enabled: false
    prometheusRules:
      enabled: false
