---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: smartctl-exporter
  namespace: flux-system
spec:
  interval: 10m0s
  provider: generic
  ref:
    tag: 0.16.0
  url: oci://ghcr.io/prometheus-community/charts/prometheus-smartctl-exporter
