---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: 4.12.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: ingress-nginx
  dependsOn:
    - name: metallb
    - name: cert-manager
  values:
    fullnameOverride: ingress-nginx
    controller:
      metrics:
        enabled: true
      ingressClassResource:
        default: true
