---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb
  namespace: metallb
spec:
  addresses:
    - 10.0.0.200-10.0.0.250
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dmz
  namespace: metallb
spec:
  addresses:
    - 10.0.4.240-10.0.4.250
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: iot
  namespace: metallb
spec:
  addresses:
    - 10.0.5.240-10.0.5.250
