---
apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale
stringData:
  client_id: ENC[AES256_GCM,data:XS/4yO6ud3x5peR+jN2YFS0=,iv:ptNyyNlXy5YZL76dm1vYra/PON8vUBIIaT22toSuQL0=,tag:lDavbdafsWQB1gMCe38JNQ==,type:str]
  client_secret: ENC[AES256_GCM,data:l1IIE0Cf2RVYFMpfiFW9yE7SLrrev05gHLkFNRTYiiRirxg9YJrInncmfbNhKGy3wjXdnE3wfJcjtNZdATdz,iv:TEIN70/hBNRB6U8t7/x0sFNTQU5JpADIfWjc36UJEKQ=,tag:/zv0f1rIZ9aScJ/YxeVIDQ==,type:str]
sops:
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWmVSMzNYSnd1R05ydEtP
        ZzFtMEJvMEdTZTgweXAraXFOcFNReGpEL2kwClphQzlXTjQ3djZYVVVUQTF2dG5r
        MCtTUFB5cEowQi9NdjNjV205cE1nZWcKLS0tIHIzYUViT2U1a3RGZWRrY3ZRemdr
        aFhhL3FSZjloRkxDUGRtU24ydWhBUDgKSBbSMhehQ2A22vsbAJz1PKDl8OE00cPo
        VDsXSyuTohS1LAvhY/+8AFL+4WE3lPbzG4oulFy8/lpqaEHAH0J+uQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-19T17:27:10Z"
  mac: ENC[AES256_GCM,data:HkjiNPRtiUxowMV3NzjvmdXCm3DLlBHFu+HbqvvJM8gvDwSH3AwBaClH3BlZIWet4AknAzgjiU8edM7otZimI81uQFZ0l3li4OIwiVCsZ6TN3fIS79VO7GgrhsMgnoYjip0IVX6HIFtLZW2dNsDk01MeT/FNTkYVRtpdNFNaHaQ=,iv:PvunCwB9HasmN8B2R2GwuHqXXuoe+SIYORHNe23OQZI=,tag:vX6cd+PGDxmuwy0zUum6rQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
