---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karakeep
  namespace: flux-system
spec:
  chart:
    spec:
      chart: karakeep
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: karakeep
      version: 0.27.0
  install:
    createNamespace: true
  interval: 1m0s
  storageNamespace: karakeep
  targetNamespace: karakeep
  valuesFrom:
  - kind: ConfigMap
    name: karakeep-config-values
