---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karakeep
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: karakeep
    namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  storageNamespace: karakeep
  targetNamespace: karakeep
  valuesFrom:
  - kind: ConfigMap
    name: karakeep-config-values
