---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
global:
  fullnameOverride: navidrome

defaultPodOptions:
  nodeSelector:
    kubernetes.io/hostname: serpentera

controllers:
  navidrome:
    containers:
      app:
        image:
          repository: docker.io/deluan/navidrome
          tag: 0.61.2

service:
  app:
    controller: navidrome
    ports:
      http:
        port: 4533

ingress:
  app:
    className: nginx
    hosts:
      - &ingress
        host: navidrome.cjf.sh
        paths:
          - path: /
            service:
              identifier: app
              port: http
      - <<: *ingress
        host: listen.cjf.sh
      - <<: *ingress
        host: music.cjf.sh
    tls:
      - hosts:
          - navidrome.cjf.sh
          - listen.cjf.sh
          - music.cjf.sh

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: zfs-dataset
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /data

  media:
    enabled: true
    type: hostPath
    hostPath: /var/tank/media/music
    globalMounts:
      - path: /music
