---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 24h0m0s
  type: oci
  url: oci://ghcr.io/immich-app/immich-charts/immich
