---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: valkey
  namespace: flux-system
spec:
  interval: 24h0m0s
  provider: generic
  ref:
    tag: 2.4.7
  url: oci://registry-1.docker.io/bitnamicharts/valkey
