apiVersion: v1
kind: Secret
metadata:
  name: coredns-omada
  namespace: coredns-omada
stringData:
  username: ENC[AES256_GCM,data:C8mp,iv:iUYHj45pqOrRlcnC5z6ikn2egn0U/YCaABMfkOMObZM=,tag:UbkEzA9n9LjyABD1V7Qbxw==,type:str]
  password: ENC[AES256_GCM,data:bTi19Z9myEtU7JVJg4UCRvE4U5DhU1QbNP5h4Fr+70s=,iv:VcxjKOQsYUbCdP1ffo7i+EwcH9p2ibYvHwC52x45jog=,tag:+NxydIdU2phZm6EnTlE1SQ==,type:str]
  url: ENC[AES256_GCM,data:VxMDU+1QH/KyJdeTyaxW/yna5qs=,iv:R3FFQV0DpKJlsIN7mQMmhgqZ31d/0fPpfXitHcYgue4=,tag:aZRC0ZhOjI0uZSwkYhbN2A==,type:str]
  site: ENC[AES256_GCM,data:SyiDIA==,iv:d9PBIHXvOurvHto1KlBYp+CwYnQJ1oKGzuWCjU4KJ6o=,tag:7LK/8rEZFgvCGWjVV9umLA==,type:str]
sops:
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMjJEWXFrNGZBS01SNEk2
        UTg0b1hrc3ZXMCtjS2d2Y0FHTWRhejdHaTFzCkpWSnpoN2pUaXpnWDdDNnJZalpz
        UFJEeTJsdkxXN0tCSGxBK3FsVzVCRGcKLS0tIE40MlBEQTFjblhaRkJkbVlMaEJz
        akJ5TCthclovcURpalh3aGN3dXBYK2cKZKkAXb3FcbJ4Zwd/0IzRYeUweoOfeWsk
        jNNbM07Iu+KeHF88fU+tMW+sqwHLUakNznht8dYzuq9ClA52k4lYgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-12T15:27:26Z"
  mac: ENC[AES256_GCM,data:Jh1liotHmgHIqUjFWqza0oULXr3092D+F77wFzeo5m1YtV8rR+lFwo62PmwLqEu1UOOSgwT4RQ6uOaPo9VJpakt2p3iyAxtao/hp1SXQGSHiw902Rzn3jxlrik5ezbF8KSBiQOgPSt8XhG8x7Ywu/xQOKbsQsfv2eV9kotG4f8Q=,iv:NfiW7wbTHgipg7MtMBEiyNvb7pcvmmWaj/ZxsS33oKE=,tag:a/VOrvTlK7Q4JeZVcJmrog==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
