---
apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres
  namespace: immich
type: kubernetes.io/basic-auth
data:
  username: ENC[AES256_GCM,data:ptVZC5xyu08=,iv:Q8KCuPNoEtKi4t062P45cBixltavD8rWsRaCem9jWKU=,tag:Rre/0lju4HdtfZ+i2OuswA==,type:str]
  password: ENC[AES256_GCM,data:uG3n8FuZOw8v3Kxn9rPJVJQbJKlUBosQ,iv:O32Y3j22k3zXyKaMS2cxZXajEq4nTDql6jAuWs6L2/s=,tag:WAGVgxmoERfUchfVAMMIsA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bERzaE0xM0VpS05MM3ow
        MTgxMTFaMW95Tk1oeG9MQVBsTnZONCtzMlhnCm9jaUFTQVVMc0hMTzdSbUNBcXNp
        M0grSDlOc3p6eUZJaG9GeStYSGlGM3MKLS0tIGN3RVhoMUJRQ3QydWoyNnlwK1JM
        azdOb2ZnWEtIbkdibnZyckdWVWlzOGcKYvpv0mYsI78KORib7lK3hVvR27wNt0Jj
        1d1yLCH1+P70400KfZBgTH4wuyzSxLMJ1r5gfQH2FC09p59hblot3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-04T16:45:14Z"
  mac: ENC[AES256_GCM,data:PpFZmKfXf5crEs4uc2Wuy8EysB7sVPFu8qm5w6wN8B1nngC/tKL6yL8OjtcGqWM5vFBJ6CaSNTYOlEXPvE+sTmD5pk3rrv1TdJiMGiNl02ihC09W2zfOVWeLg7UhsHwlldL1uUH14YX4d21npUzm5E8ROQM419KF87ez/LMy994=,iv:XhSrExJOIT7NypUzJBbu7Nefytf7x8NMvIIP2zhmBZc=,tag:ABmFJFk/54CW5x5496dfBA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: immich
spec:
  # At the time of writing, immich is only compatible with pgvecto.rs <0.4. Latest postgres image with that version is 16.5.
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.5-v0.3.0@sha256:be3f025d79aa1b747817f478e07e71be43236e14d00d8a9eb3914146245035ba
  instances: 1
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  managed:
    roles:
      - name: immich
        superuser: true
        login: true
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgres
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;
  storage:
    size: 4Gi
    storageClass: openebs-hostpath
