---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  storageClassName: zfs-dataset
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200G
