---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-redis
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: valkey
    namespace: flux-system
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: immich
  values:
    fullnameOverride: valkey
    replica:
      replicaCount: 1
    auth:
      enabled: false
    global:
      defaultStorageClass: zfs-dataset
