---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-redis
  namespace: immich
spec:
  chart:
    spec:
      chart: valkey
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: valkey
        namespace: flux-system
      version: 0.9.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: immich
  values:
    fullnameOverride: immich-redis
    replica:
      replicaCount: 1
    auth:
      enabled: false
    global:
      defaultStorageClass: zfs-dataset
