---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: flux-system
spec:
  chart:
    spec:
      chart: immich
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      version: 0.9.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: immich
  values:
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-library
