---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: immich
    namespace: flux-system
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: immich
  values:
    image:
      tag: v2.2.3
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-library
    env:
      REDIS_HOSTNAME: immich-redis
      DB_HOSTNAME: immich-db-rw
      DB_USERNAME: immich
      DB_DATABASE_NAME: immich
      DB_PASSWORD:
        secretKeyRef:
          name: immich-db
          key: password
    server:
      service:
        main:
          type: LoadBalancer
      ingress:
        main: &ingress
          enabled: true
          annotations:
            # proxy-body-size is set to 0 to remove the body limit on file uploads
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
          ingressClassName: nginx
          hosts:
            - host: pics.cjf.sh
              paths:
                - path: /
          tls:
            - hosts:
                - pics.cjf.sh
