---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: immich
    namespace: flux-system
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: immich
  values:
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-library
