---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: immich-db
  namespace: immich
spec:
  length: 32
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db
  namespace: immich
spec:
  refreshPolicy: CreatedOnce
  target:
    name: immich-db
    template:
      data:
        username: immich
        password: "{{.password}}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: immich-db
