apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres
  namespace: immich
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:Pg6AdZPXVy5EfjBIqrTIRQ==,iv:aoYMKl0fhmjkZ4UliA4zYZx1lEBbqPDCYZ9usC8fIE8=,tag:XugKHJshbZ7YDlWSFtkL9Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaTNUVmcwNUEvTExYd3R1
        Z1FsOEdVNVlSU0t3Zmc4enhpSHRpMjZEUHlFCm53QU93WFRDS2o1UFJ6L3VUNHhX
        ZFRBSlNENURJUTBJSkVPeS9QdFRpeHcKLS0tIFlXUzFDcVhvYTBEc1ArNU45SEVF
        aXYwZ1FDdm5GL0FnaFI5cVhCcDN2a28K7A7XurMmTksZSrJmc9qM6a0Xsll1Hl7K
        +RVUfCCE/EyHyarb6zCV4m3bQoD0siRb6LpomxsFzwdnez2PnmZHjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-04T03:17:45Z"
  mac: ENC[AES256_GCM,data:BXNqADpLDCorhM86vHlYeiwIbrsxICMCQU1A5siSObE1LnIMEE0v/WKifU+SHOEi7tZC9JXPZ4e1Lwev54b2NxQfU5OQWxcpZ50dtpoHL9fywEKc2lIUghdV4u8n706Y2N4E893BcOH9ZTExZK7/15f/l0jpfJPqfoQhTyA4k9U=,iv:FGIGXB6K056xEx8y+oyMadLZrvfDTw9rcm9PGhW+Ej4=,tag:OKdC8gBtOV5VT2jT1P4YXQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
