---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-dataset
provisioner: zfs.csi.openebs.io
allowVolumeExpansion: true
parameters:
  recordsize: 128k
  thinprovision: "no"
  fstype: zfs
  poolname: tank
