---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web-automated
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: calibre-web-automated
    namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: calibre-web-automated
  valuesFrom:
    - kind: ConfigMap
      name: calibre-web-automated-config-values