---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: psmdb-db
  namespace: flux-system
spec:
  chart:
    spec:
      chart: psmdb-db
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: psmdb-db
      version: 1.21.1
  install:
    createNamespace: true
  interval: 1m0s
  storageNamespace: psmdb-db
  targetNamespace: psmdb-db
  valuesFrom:
  - kind: ConfigMap
    name: psmdb-db-config-values
