---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  values:
    controllers:
      openebs:
        containers:
          app:
            image:
              repository: ghcr.io/cinnyapp/cinny
              tag: v3.2.0
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      app:
        controller: openebs
        type: LoadBalancer
        ports:
          http:
            port: 80
