---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: frigate
spec:
  interval: 2m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      frigate:
        containers:
          app:
            image:
              repository: ghcr.io/blakeblackshear/frigate
              tag: stable
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                gpu.intel.com/i915: 1
              limits:
                gpu.intel.com/i915: 1

    service:
      app:
        controller: frigate
        ports:
          http:
            port: 8971

    ingress:
      app:
        hosts:
          - host: frigate.cjf.sh
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        type: emptyDir
      config-file:
        type: configMap
        name: frigate-config
        globalMounts:
          - path: /config/config.yml
            subPath: config.yml
            readOnly: true
      storage:
        type: hostPath
        hostPath: /srv/frigate/storage
        hostPathType: DirectoryOrCreate
        advancedMounts:
          frigate:
            app:
              - path: /media/frigate
      tmpfs:
        type: emptyDir
        medium: Memory
        advancedMounts:
          frigate:
            app:
              - path: /tmp/cache
      dev-shm:
        type: emptyDir
        medium: Memory
        advancedMounts:
          frigate:
            app:
              - path: /dev/shm
