---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
  namespace: multus
spec:
  config: |
    {
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.0.5.0/24",
        "rangeStart": "10.0.5.240",
        "rangeEnd": "10.0.5.250",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
      }
    }
