---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hass
  namespace: flux-system
spec:
  chart:
    spec:
      chart: app-template
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: hass
  values:
    global:
      fullnameOverride: hass
    controllers:
      hass:
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [
                {
                  "name":"multus-iot",
                  "namespace": "kube-system"
                },
                {
                  "name":"multus-dmz",
                  "namespace": "kube-system"
                }
              ]
        containers:
          app:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2024.4
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
                  - NET_RAW
                  - NET_BROADCAST

    service:
      app:
        controller: hass
        ports:
          http:
            port: 8123

    ingress:
      app: &ingress
        className: nginx
        hosts:
          - host: hass.cjf.sh
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - hass.cjf.sh

      tailscale:
        <<: *ingress
        className: tailscale

    persistence:
      config:
        name: hass-config
        type: configMap
        advancedMounts:
          hass:
            app:
              - path: /config/configuration.yaml
                subPath: configuration.yaml

    configMaps:
      config:
        data:
          configuration.yaml: |
            default_config:

            http:
              use_x_forwarded_for:
                true
              trusted_proxies:
                - 0.0.0.0/0

            ffmpeg:
