apiVersion: v1
kind: Secret
metadata:
  name: hass
  namespace: hass
stringData:
  prometheus_token: ENC[AES256_GCM,data:+lAXG5zYN4j5RByjuLzFgzX+GhVAFHOtSycMCU9aGVdENTIEOwj9Fk82d721R0rQ852iPdAxkGIOKhv8QOZThjSptEK3BdSNtkM7hHFBgHklkJCV9TX7P19a/cnlk8GQboOPIQ4+rHvX+2Jjfssrq7yCZZmW5BArepY0bSNBwznT8SsVWHwUw1m+IQkjbJQPS450mA8H/KvqlUEWvEcyONnbix9KQpFOuOKXd/DmHhJEfJAqLnyD,iv:ZtKJjdKRsJhHhHvsYRZ0wMJ3LU+GRvMQs60k+oECN8w=,tag:txQThv+Z/GiCrkMQQRFjVw==,type:str]
sops:
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Tyt4dmJaMW1YdXZHK01F
        emwvRnJEV0dFK2VFdHdWZjZsMmtieUYxYm5vClpHblk4YnkxMVhxT1RrZjhheU1j
        cm5GSWFPU3p6emhpWTZuS2o0YUFHZkEKLS0tIGR5TkdZRlJhUUo4emFIaGNsRVB6
        Yyt5eW5Qem5qZXJQcVNqSnpLKzdUc0kK3R/J81fBc/Cc55YfJKiaqDd5yhmJMLl/
        5p1PZUXIJXfG6cNGR/SMeqgZsElUYeEs2UarS0DygnvD5KM+v0vP4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T02:11:03Z"
  mac: ENC[AES256_GCM,data:Amj5AWcI4c0wInsd3pAJzwnA/p9zaVthohTMAxBH+Y9wGKSJ0+3SceIxxXbL4ObhvzbxJ9dHuIXNITWN4gTg+nY0lJHyX0aZF60KdICL9MxPV8BO9o4gbAd2VSsGBUnCOoDzW+dxu1TEeiQ5i8BnIKyKnDH10Af01iAPao2DCS4=,iv:xveUC0U3Sx0BA009X6bMsSoSOuv2Kx9L+3PP1DIWjLU=,tag:NybHO2/4zvZVAzrfx//2zg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
