---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: cert-manager
    namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: cert-manager
  valuesFrom:
  - kind: ConfigMap
    name: cert-manager-config-values
