---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: loki
      version: 6.46.x
  install:
    createNamespace: true
  interval: 1m0s
  storageNamespace: loki
  targetNamespace: loki
  valuesFrom:
  - kind: ConfigMap
    name: loki-config-values
