---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: promtail
  chart:
    spec:
      chart: loki-stack
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 2.10.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: monitoring
