---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: mealie
    namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: mealie
  valuesFrom:
    - kind: ConfigMap
      name: mealie-config-values
