---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
  namespace: flux-system
spec:
  chart:
    spec:
      chart: app-template
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: mealie
  values:
    global:
      fullnameOverride: mealie
    controllers:
      jellyfin:
        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v2.4.2
            env:
              ALLOW_SIGNUP: "false"
              PUID: "1000"
              PGID: "1000"
              TZ: America/New_York
              BASE_URL: https://recipes.cjf.sh

    service:
      app:
        controller: mealie
        ports:
          http:
            port: 9000

    ingress:
      app: &ingress
        className: nginx
        hosts:
          - host: recipes.cjf.sh
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - recipes.cjf.sh

      tailscale:
        <<: *ingress
        className: tailscale

    persistence:
      config: &p
        type: persistentVolumeClaim
        storageClass: zfs-dataset
        accessMode: ReadWriteOnce
        size: 5Gi
        globalMounts:
          - path: /app/data
