---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: operator
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
      version: 7.1.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: minio
