---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: qbittorrent
    namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  storageNamespace: qbittorrent
  targetNamespace: qbittorrent
  valuesFrom:
  - kind: ConfigMap
    name: qbittorrent-config-values
