---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb
spec:
  type: oci
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts/metallb
