---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: pocket-id
    namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  storageNamespace: pocket-id
  targetNamespace: pocket-id
  valuesFrom:
  - kind: ConfigMap
    name: pocket-id-config-values
