---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: pocket-id
  namespace: flux-system
spec:
  interval: 10m0s
  provider: generic
  ref:
    tag: 1.15.0
  url: oci://ghcr.io/hobbit44/pocket-id-helm/pocket-id
