---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whisper
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: whisper
    namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: whisper
  valuesFrom:
  - kind: ConfigMap
    name: whisper-config-values
