---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs
  namespace: flux-system
spec:
  chart:
    spec:
      chart: seaweedfs
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: seaweedfs
      version: 4.0.409
  install:
    createNamespace: true
  interval: 1m0s
  storageNamespace: seaweedfs
  targetNamespace: seaweedfs
  valuesFrom:
  - kind: ConfigMap
    name: seaweedfs-config-values
