---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweedfs-creds
  namespace: seedweedfs
spec:
  refreshInterval: "1h"
  target:
    name: seaweedfs-creds
    template:
      data:
        seaweedfs_s3_config: |-
          {
            "identities": [
              {
                "name": "admin",
                "credentials": [
                  {
                    "accessKey": "{{ .randAlphaNum 16 }}",
                    "secretKey": "{{ .randAlphaNum 32 }}"
                  }
                ],
                "actions": [
                  "Admin",
                  "Read",
                  "Write"
                ]
              },
              {
                "name": "loki",
                "credentials": [
                  {
                    "accessKey": "{{ .randAlphaNum 16 }}",
                    "secretKey": "{{ .randAlphaNum 32 }}"
                  }
                ],
                "actions": [
                  "Read",
                  "Write"
                ]
              }
            ]
          }
