---
apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-creds
  namespace: seaweedfs
stringData:
  admin_access_key: "{{ .randAlphaNum 16 }}"
  admin_secret_key: "{{ .randAlphaNum 32 }}"
  loki_access_key: "{{ .randAlphaNum 16 }}"
  loki_secret_key: "{{ .randAlphaNum 32 }}"
  seaweedfs_s3_config: |-
    {
      "identities": [
        {
          "name": "admin",
          "credentials": [
            {
              "accessKey": "{{ .randAlphaNum 16 }}",
              "secretKey": "{{ .randAlphaNum 32 }}"
            }
          ],
          "actions": [
            "Admin",
            "Read",
            "Write"
          ]
        },
        {
          "name": "loki",
          "credentials": [
            {
              "accessKey": "{{ .randAlphaNum 16 }}",
              "secretKey": "{{ .randAlphaNum 32 }}"
            }
          ],
          "actions": [
            "Read",
            "Write"
          ]
        }
      ]
    }
