---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: admin-access-key
  namespace: seaweedfs
spec:
  length: 16
  symbols: 0
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: admin-secret-key
  namespace: seaweedfs
spec:
  length: 32
  symbols: 0
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: loki-access-key
  namespace: seaweedfs
spec:
  length: 16
  symbols: 0
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: loki-secret-key
  namespace: seaweedfs
spec:
  length: 32
  symbols: 0
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweedfs-creds
  namespace: seaweedfs
spec:
  refreshInterval: "1h"
  target:
    name: seaweedfs-creds
    template:
      data:
        seaweedfs_s3_config: |-
          {
            "identities": [
              {
                "name": "admin",
                "credentials": [
                  {
                    "accessKey": "{{ .randAlphaNum 16 }}",
                    "secretKey": "{{ .randAlphaNum 32 }}"
                  }
                ],
                "actions": [
                  "Admin",
                  "Read",
                  "Write"
                ]
              },
              {
                "name": "loki",
                "credentials": [
                  {
                    "accessKey": "{{ .randAlphaNum 16 }}",
                    "secretKey": "{{ .randAlphaNum 32 }}"
                  }
                ],
                "actions": [
                  "Read",
                  "Write"
                ]
              }
            ]
          }
