---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: admin-access-key
  namespace: seaweedfs
spec:
  length: 16
  symbols: 0
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: admin-secret-key
  namespace: seaweedfs
spec:
  length: 32
  symbols: 0
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: loki-access-key
  namespace: seaweedfs
spec:
  length: 16
  symbols: 0
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: loki-secret-key
  namespace: seaweedfs
spec:
  length: 32
  symbols: 0
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweedfs-creds
  namespace: seaweedfs
spec:
  refreshInterval: "1h"
  target:
    name: seaweedfs-creds
    template:
      data:
        seaweedfs_s3_config: |-
          {
            "identities": [
              {
                "name": "admin",
                "credentials": [
                  {
                    "accessKey": "{{ .admin_access_key }}",
                    "secretKey": "{{ .admin_secret_key }}"
                  }
                ],
                "actions": [
                  "Admin",
                  "Read",
                  "Write"
                ]
              },
              {
                "name": "loki",
                "credentials": [
                  {
                    "accessKey": "{{ .loki_access_key }}",
                    "secretKey": "{{ .loki_secret_key }}"
                  }
                ],
                "actions": [
                  "Read",
                  "Write"
                ]
              }
            ]
          }
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: admin-access-key
      rewrite:
        - regexp:
            source: password
            target: admin_access_key
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: admin-secret-key
      rewrite:
        - regexp:
            source: password
            target: admin_secret_key
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: loki-access-key
      rewrite:
        - regexp:
            source: password
            target: loki_access_key
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: loki-secret-key
      rewrite:
        - regexp:
            source: password
            target: loki_secret_key
