---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: zigbee2mqtt-password
  namespace: zigbee2mqtt
spec:
  length: 32
  symbols: 0
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt-password
  namespace: zigbee2mqtt
spec:
  refreshInterval: "30m"
  target:
    name: zigbee2mqtt-password
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: zigbee2mqtt-password
