---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      zigbee2mqtt:
        containers:
          app:
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 1.39.0
            env:
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT: "true"
              ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"
              ZIGBEE2MQTT_CONFIG_FRONTEND: "true"
              ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: zigbee2mqtt
              ZIGBEE2MQTT_CONFIG_MQTT_SERVER: "mqtt://emqx.emqx.svc.cluster.local"
              ZIGBEE2MQTT_CONFIG_MQTT_USER: zigbee2mqtt
              ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: zigbee2mqtt-password
                    key: password
              # ZIGBEE2MQTT_CONFIG_SERIAL_PORT: /dev/ttyUSB0
              ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_ENTITY_ATTRIBUTES: "false"
              ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_API: "false"
              ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_AVAILABILITY_OPTIONS: "false"
              ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_LEGACY: "false"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10

    service:
      app:
        controller: zigbee2mqtt
        ports:
          http:
            primary: true
            port: 8080
          metrics:
            port: 9000

    ingress:
      app:
        hosts:
          - host: zigbee2mqtt.cjf.sh
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 100Mi
        globalMounts:
          - path: /app/data
            readOnly: false
