---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cinny
  namespace: cinny
spec:
  chartRef:
    kind: OCIRepository
    name: cinny
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: cinny
  values:
    global:
      fullnameOverride: cinny
    controllers:
      chat:
        containers:
          app:
            image:
              repository: ghcr.io/cinnyapp/cinny
              tag: v4.10.0
    service:
      app:
        controller: chat
        type: LoadBalancer
        ports:
          http:
            port: 80
    ingress:
      app: &ingress
        className: nginx
        hosts:
          - host: chat.cjf.sh
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - chat.cjf.sh
