---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      jellyfin:
        containers:
          app:
            image:
              repository: docker.io/jellyfin/jellyfin
              tag: latest
    service:
      app:
        controller: jellyfin
        ports:
          http:
            port: 8096
    ingress:
      app:
        className: nginx
        hosts:
          - host: "media.cjf.sh"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - media.cjf.sh
