---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      jellyfin:
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: docker.io/jellyfin/jellyfin
              tag: latest
            env:
              JELLYFIN_PublishedServerUrl: http://media.cjf.sh
            resources:
              requests:
                gpu.intel.com/i915: 1
              limits:
                gpu.intel.com/i915: 1
    service:
      app:
        controller: jellyfin
        ports:
          http:
            port: 8096
    ingress:
      app:
        className: nginx
        hosts:
          - host: "media.cjf.sh"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - media.cjf.sh
    persistence:
      config:
        type: hostPath
        hostPath: /srv/jellyfin/config
        hostPathType: DirectoryOrCreate
        advancedMounts:
          jellyfin:
            app:
              - path: /config
      cache:
        type: emptyDir
        advancedMounts:
          jellyfin:
            app:
              - path: /cache
      media:
        type: nfs
        server: 10.0.0.70
        path: /var/tank/media
        advancedMounts:
          jellyfin:
            app:
              - path: /media
