---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: chat
  namespace: chat
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    controllers:
      chat:
        containers:
          web:
            image:
              repository: ghcr.io/cinnyapp/cinny
              tag: v3.2.0
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      chat:
        controller: chat
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: 80
    ingress:
      chat:
        className: nginx
        hosts:
          - host: "chat.cjf.sh"
            paths:
              - path: /
                service:
                  identifier: chat
                  port: http
        tls:
          - hosts:
              - chat.cjf.sh
