---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mimir-distributed
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 5.6.x
  install:
    createNamespace: true
  interval: 30m0s
  timeout: 10m0s
  targetNamespace: monitoring
  dependsOn:
    - name: kube-prometheus-stack
  values:
    fullnameOverride: mimir
    mimir:
      structuredConfig:
        limits:
          # The rules created by the prometheus chart require a higher limit than the default
          ruler_max_rules_per_rule_group: 30
        blocks_storage:
          storage_prefix: blocks
        alertmanager_storage:
          storage_prefix: alertmanager
        ruler_storage:
          storage_prefix: ruler
    minio:
      enabled: true
    metaMonitoring:
      serviceMonitor:
        enabled: true
      dashboards:
        enabled: true
      prometheusRule:
        enabled: true
        mimirAlerts: true
        mimirRules: true
        namespace: monitoring
