---
apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: zigbee-coordinator
  namespace: akri
spec:
  capacity: 1
  discoveryHandler:
    discoveryDetails: |
      groupRecursive: true
      udevRules:
        - ATTRS{product}=="Sonoff Zigbee 3.0 USB Dongle Plus"
    name: udev
