---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emqx
  namespace: emqx
spec:
  interval: 5m
  chart:
    spec:
      chart: emqx
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
      interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    persistence:
      enabled: true
    metrics:
      enable: true
    ingress:
      mqtt:
        enabled: true
        hosts:
          - mqtt.cjf.sh
        tls:
          - hosts:
              - mqtt.cjf.sh
      dashboard:
        enabled: true
        hosts:
          - emqx.cjf.sh
        tls:
          - hosts:
              - emqx.cjf.sh
