---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name chat
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: bjw-s
  values:
    controllers:
      app:
        containers:
          web:
            image:
              repository: ghcr.io/cinnyapp/cinny
              tag: 3.2.0
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      app:
        controller: *name
        ports:
          http:
            port: 80
    ingress:
      app:
        enabled: true
        className: "external-nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-ext.bjw-s.dev
        hosts:
          - host: hass.bjw-s.dev
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: home-assistant-config
        advancedMounts:
          home-assistant:
            app:
              - path: /config
      deploy-key:
        type: secret
        name: home-assistant-secret
        defaultMode: 256
        globalMounts:
          - path: /root/.ssh/id_rsa
            subPath: GH_DEPLOY_KEY
