---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name chat
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: bjw-s
  values:
    controllers:
      app:
        containers:
          web:
            image:
              repository: ghcr.io/cinnyapp/cinny
              tag: 3.2.0
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      app:
        controller: *name
        ports:
          http:
            port: 80
