---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tenant
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
      version: 7.1.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: monitoring
  dependsOn:
    - name: kube-prometheus-stack
    - name: minio-operator
  values:
    tenant:
      name: fielder
      pools:
        - servers: 4
          name: pool
          volumesPerServer: 4
          size: 10Gi
          storageClassName: zfs-dataset
      metrics:
        enabled: true
