---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: sonarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    controllers:
      sonarr:
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/sonarr
              tag: 4.0.8
            env:
              PUID: 1000
              PGID: 1000
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      app:
        controller: sonarr
        ports:
          http:
            port: 8989
    ingress:
      app:
        className: nginx
        hosts:
          - host: sonarr.cjf.sh
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - sonarr.cjf.sh
    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 2Mi
        globalMounts:
          - path: /config
            readOnly: false
      media:
        type: nfs
        server: 10.0.0.70
        path: /var/tank/daijinryuu/media
        advancedMounts:
          sonarr:
            app:
              - path: /media
      nzbget:
        type: nfs
        server: 10.0.0.70
        path: /var/tank/daijinryuu/nzbget
        advancedMounts:
          sonarr:
            app:
              - path: /downloads
