---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metallb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metallb
      version: 0.15.x
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: metallb
  valuesFrom:
  - kind: ConfigMap
    name: metallb-config-values
