---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
  namespace: flux-system
spec:
  chart:
    spec:
      chart: garage
      sourceRef:
        kind: GitRepository
        name: garage
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: garage
  valuesFrom:
    - kind: ConfigMap
      name: garage-config-values
