---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: garage
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/stefanprodan/podinfo
  ref:
    tag: "v2.1.0"
  sparseCheckout:
    - script/helm/garage
