---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: flux-system
spec:
  chart:
    spec:
      chart: app-template
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: frigate
  values:
    controllers:
      frigate:
        containers:
          app:
            image:
              repository: ghcr.io/blakeblackshear/frigate
              tag: stable
            envFrom:
              - secretRef:
                  name: frigate-secret

    service:
      app:
        controller: frigate
        ports:
          http:
            port: 8971
          feed:
            port: 5000

    ingress:
      app:
        className: nginx
        hosts:
          - host: frigate.cjf.sh
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - frigate.cjf.sh

    persistence:
      config:
        type: configMap
        name: frigate-config
        advancedMounts:
          frigate:
            app:
              - path: /config/config.yml
                subPath: config.yml
      storage:
        enabled: true
        type: hostPath
        hostPath: /var/tank/frigate/storage
        globalMounts:
          - path: /media/frigate
      tmpfs:
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /tmp/cache
      cache:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 2Gi
        globalMounts:
          - path: /dev/shm
