---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: frigate
    namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  storageNamespace: frigate
  targetNamespace: frigate
  valuesFrom:
  - kind: ConfigMap
    name: frigate-config-values
