---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguardhome
  namespace: adguardhome
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    controllers:
      adguardhome:
        containers:
          app:
            image:
              repository: docker.io/adguard/adguardhome
              tag: "v0.107.52"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      app:
        controller: adguardhome
        type: LoadBalancer
        ports:
          http:
            port: 80
          init:
            port: 3000
          dns:
            port: 53
            protocol: UDP
    ingress:
      app:
        className: nginx
        hosts:
          - &ingress
            host: dns.cjf.sh
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - <<: *ingress
            host: init-dns.cjf.sh
            paths:
              - path: /
                service:
                  identifier: app
                  port: init
        tls:
          - hosts:
              - dns.cjf.sh
              - init-dns.cjf.sh
    persistence:
      work:
        type: emptyDir
        globalMounts:
          - path: /work
            readOnly: false
      config:
        type: hostPath
        hostPath: /srv/adguardhome/config
        hostPathType: DirectoryOrCreate
        globalMounts:
          - path: /conf
            readOnly: false
