---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mattermost-db
  namespace: mattermost
spec:
  instances: 1
  bootstrap:
    initdb:
      database: mattermost
      encoding: utf8
      owner: mattermost
  storage:
    size: 4Gi
    storageClass: zfs-dataset
