---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mattermost-db-creds
  namespace: mattermost
spec:
  refreshInterval: "1h"
  target:
    name: mattermost-db-creds
    template:
      data:
        loki_access_key: "{{ .loki_access_key }}"
  data:
    - secretKey: mattermost-db-app
      remoteRef:
        key: fqdn-uri
