apiVersion: v1
kind: Secret
metadata:
  name: mattermost
  namespace: mattermost
stringData:
  DB_CONNECTION_CHECK_URL: ENC[AES256_GCM,data:wd7/4TQWsVBiZ3L85StxKP6cy4gYP5slIIuPu4u6uKhu9mrxNt85jrlHxdZ4yjaLMcC7wGeFUJEIzGkF0NQAyGJKo0E6a66+FBky1E9Ms9/T0jVDRSqpgsuydRV4vthTGLUyIo+5Sg+dd2meWLVdDApoNopY,iv:24Mx1NzIKmyUayJmDkjXDnaw0ZpnfsI+SKZon3z57uE=,tag:2/D7+vq2V0M0GgRXcmBaVQ==,type:str]
  DB_CONNECTION_STRING: ENC[AES256_GCM,data:sryJHslFzhiHEIX4qTb34JvHzZkc5Y3YPRtSIt+CFaFYHuykWFkKcPMWWGPwx4fGKAS63p063yvuWt30QLq+Qg5U4rKpJ5zAidydRfPMHT9peiuBBpVJwgRPE2DSG0X/el8ofa+Q2Ii3Xxc8A21bi6MYDHwN,iv:s0ttDwhg8rCkM862OlrUu2z8G7NfTxtvSxk+NbyZl44=,tag:Cebc3QQjG1C9EmKP9RqUGA==,type:str]
  username: ENC[AES256_GCM,data:uTgNdgL0RDCO2g==,iv:pu6reV9dy0r0XikbpmwiAXRDcIZLs8VUUCSPblGj3d4=,tag:k1aKwjNuuBLVLNBObzatsQ==,type:str]
  password: ENC[AES256_GCM,data:mdX+I3hSVw5aDMAA3+jvRBHchX3Uy8emCO6HXWuQHzY=,iv:93c4/c08Zp1wjlRKYl0bJVn+Vc/chEbOcZbU4hoo/E4=,tag:l+9Iq0UNTkzAD3xLb4XlaQ==,type:str]
sops:
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWE9sUGFxd09GRTFpYmpr
        VDY1UjMwU1pzNXd4MFZVck5BQ3h1Q2tiZHhjClRnZXdiQTY2VjYwMWZ2aDh4KzVt
        L0R2U25yRXhHdmxsVGhqQlZTTWdJSUUKLS0tIHVHdlhPcG0rUHlQSnpRc3B1RnRj
        VUtrSzdhZEZKd1FZUVJON1UwcmZWYnMKz7LMHQ4/2y7tUsY77F1r+pNbMhExpkHg
        kkjZAk69B5l5e0bNcqu/56LISyTyBK7inluby1YxpHn2dRGg0Xbm2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T04:24:34Z"
  mac: ENC[AES256_GCM,data:QbfT0F9oWHLif5djvV6jUPyKEa9/fS/Jc8GYrMwHtv8Ae35KodGPbCLsBgTcIHbvtJT7HDFZDvwo6YSr7FubcmLJMlMY9wyQs+CeebzmWuyNQ+SIVhiLxb+PA0cJ59iBsHOjZyp34UlAmEgEQD3mSq41zCPgbKed3quZIAXYD0w=,iv:CsHJ4vrPd4FsNFOEvKmGdW4dfjARzgbdRtGmo8jgWow=,tag:vy/Gej9oJN+2UKDyS+2LLQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
