---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost
  namespace: mattermost
spec:
  storageClassName: zfs-dataset
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
