---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: audiobookshelf
    namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: audiobookshelf
  valuesFrom:
  - kind: ConfigMap
    name: audiobookshelf-config-values
