---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-cluster
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cluster
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
      version: 0.2.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: cluster
