---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  chart:
    spec:
      chart: promtail
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 6.16.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: monitoring
  dependsOn:
    - name: kube-prometheus-stack
  values:
    fullnameOverride: promtail
    serviceMonitor:
      enabled: true
    config:
      clients:
        - url: http://monitoring-loki-stack:3100/loki/api/v1/push
