---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kavita
  namespace: flux-system
spec:
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kavita
      version: 5.0.1
  install:
    createNamespace: true
  interval: 1m0s
  storageNamespace: kavita
  targetNamespace: kavita
  valuesFrom:
  - kind: ConfigMap
    name: kavita-config-values
