---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
global:
  fullnameOverride: kavita

controllers:
  kavita:
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/kavita
          tag: 0.9.0
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: America/New_York

service:
  app:
    controller: kavita
    ports:
      http:
        port: 5000

ingress:
  app:
    className: nginx
    annotations:
      # proxy-body-size is set to 0 to remove the body limit on file uploads
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    hosts:
      - host: kavita.cjf.sh
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - kavita.cjf.sh

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: zfs-dataset
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /config

  books:
    type: nfs
    path: /var/tank/media/kavita/books
    server: 192.168.200.13
    globalMounts:
      - path: /books
