---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recipes-app
  namespace: recipes
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    controllers:
      recipes:
        containers:
          app:
            image:
              repository: docker.io/vabene1111/recipes
              tag: "1.5"
            env:
              DB_ENGINE: django.db.backends.postgresql
              POSTGRES_DB: tandoor
              POSTGRES_HOST: recipes-db-postgresql-0
              POSTGRES_PORT: 5432
              POSTGRES_USER: tandoor
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: recipes-db-postgresql
                    key: password
              SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: secret-key
                    key: password
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      app:
        controller: recipes
        ports:
          http:
            port: 8080
    ingress:
      app:
        className: nginx
        hosts:
          - host: recipes.cjf.sh
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - recipes.cjf.sh
    persistence:
      staticfiles:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 2Gi
        globalMounts:
          - path: /opt/recipes/staticfiles
            readOnly: false
      mediafiles:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 2Gi
        globalMounts:
          - path: /opt/recipes/mediafiles
            readOnly: false
