---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rocketchat
  namespace: flux-system
spec:
  chart:
    spec:
      chart: rocketchat
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rocketchat
      version: 6.27.1
  install:
    createNamespace: true
  interval: 1m0s
  storageNamespace: rocketchat
  targetNamespace: rocketchat
  valuesFrom:
  - kind: ConfigMap
    name: rocketchat-config-values
