---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: paperless
    namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  storageNamespace: paperless
  targetNamespace: paperless
  valuesFrom:
  - kind: ConfigMap
    name: paperless-config-values
