---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: paperless-ngx
  namespace: flux-system
spec:
  interval: 10m0s
  provider: generic
  ref:
    tag: 4.5.0
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
