apiVersion: v1
kind: Secret
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
stringData:
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:IJNvb4+ncgLsnKbnHs4Ivx7Q6dw1uYOce69DtBGB1U3MMlG0sxDAk5e7kF+UpM6PaG8SNlbwVrkTcG0TFUgbssJR8E9oEWawr6UqwFnLCcHFsrsyJljt92A9SlqYJ3HPucazhPmgLbPY3YyGf2r++U/WJUUnQSNWqy5UL09/yVYx9Vqhr79DrMWWomsXYBLo2ZS2bMadJJMczDi/6HskO4bPYZfW7ohOuVeXoP9W1Obx/Hjq5OsCwoE3YpT6F1SRhdCGVfiC3RE0snqzdmcz2EmO+VvKg5RmB8RKMIQN+eIqLTl5mXQkNhIEWJLGWRuTg7yDLJhlm9/F3z1p/qhkZ5HXfQWDviOdf47EwGEz0q8ntijPTZ4ZjyGEgotVOtbMGgxh8ri8Og3kgVic4L4J4ATDiOkSB/2hfkVnnwIB,iv:bNJ9FrhUzSwyu0CvQzP/7pKzCogHdIsICtCwhZcmGnA=,tag:sifyHD4IuSO2Y437PoEmQg==,type:str]
sops:
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWG1lSUJ3cGV4bTZ1TDA5
        OVc2KzdyUXkxTUt4R1BjaTJlZnkyS1pWSW13CmZSQmlmSFNwM0ZGWEY2UkpBQmRu
        Z0hNSW1sZTNuNmxlMjUydE9NSFNFZFUKLS0tIG14R1VDbFN4enVLK0hpcndvS0c2
        aWVubFNlUG5rK0M5WWU0eWRIY284SGMK/WP7cNtd3FixF6HQiGbmJQOY5io26xbE
        sFz/HIjFATouNvGh753BZ2+w4UVRJ4upDLF9F+MRcweKPQRaE033lw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T18:31:29Z"
  mac: ENC[AES256_GCM,data:JBrDUQBYLuqvbhMcmFYILUsq6qbB8qzTNR8ejWGISNnnRRLn6xYMB0i3DGVHr9pAUWeZ1ecV8wrbrcQkYzwoFonwTRX7W8PLK+P5VXLmqHkKavpO3nQ8RuRZqqBUXeSKh8HvKvlIZy02ZUYNtgQiB1uB5bktvWlv0JkiuA9LG5Q=,iv:2dRnfDBjRfVBQemwinPsPeaMlCnaiESjwXST92G5twQ=,tag:IRkQosk2rg4AmQlA/RD4iw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
