apiVersion: v1
kind: Secret
metadata:
  name: paperless-ngx
  namespace: paperless
stringData:
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:e67QGTq0tInQGK4P0Kje+bomZfI2KgkmvYooptW9MuotKeTqBEBxXs+fLVwQ9r2J/tRfPOlz36krOZKALCSf2wMzOnQpxv6eSb7NeI0ItmP+1W3qoXJHCqeiYAjKom/8nTi0HnaFxShIxVtCN5/0L/plo4PWYwnmB4nkkNcJ5fW5SM/LeWTTPj/OQH0zIsbtiHLh2y1lKODliswBjmt3LIF0z3ECtG2UrWwHK03VMWFzQvtW2UCpGXaL9bNq07/6MhHzrpogM904OQfBeS6lctYdom9IEx9tCMIh8brdqRup63pnVx/28uB/9Fr3OYr4xUG9nhVMbhnk/3jAvcw4SUobQaK6frVIIlDItnnBsYsl9rD3ub/Uo8LBSRScoPQGplTOwNtW1zJ/KMWDavteXwZpjuHf8c2jKBNSFqHbKFafIQEbwtZWeMmP0VxEU0sGD3xldt2AYV2H00FQcq7e+40Iidbg91uUGqufSUjAbZ4qimW2jJhi8iBN/HqEeBYuibqz+rfMTNQ=,iv:/9COJKGQijU1fxWZ3PSe4ZbRK74LBkj3dQxnh8zOjOE=,tag:v408Y0mCDaMlvLYYgbWuPw==,type:str]
sops:
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyU0RJVDVMQVM4NjZOZmN6
        QXduVjI5akpxeUJnN0NTenpoTXRXQWJnVW1ZCnZYTlVFbi9kaURaQWR2Wm1pcEdp
        K0gxMGpya1BBaCtvcTdFVktUNmdTMXcKLS0tIHJiSWdtUy8yMzEzMUtuQjR2NjUy
        MzBGSC9xTkdkNVR5UXNvM3RvV1l3L2sKAvpuoLYyNmk8+YzjAI8tPPWyHRKKecdF
        qtEdV+ZWWzor3+VYKb5LBpnCDevSz8DOwerOiyenlmDvlQD5+TsTQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T00:48:29Z"
  mac: ENC[AES256_GCM,data:ta3L+Qd+fNc172xoqfp0vywMiJ7Bu8t5BDq58svs06/rXSYqNOxRAm/zrwesuQ4npV/z323hGLpMh/QQFjvRrj+0gPuZytw28PLqOxAei4mYrCe2NyK/nNIB2ZC5UKCtwdf/blgRFZhJaiKdZdm8CJOkq38dev85aDxlAi84Rwk=,iv:7Ig8xupCX1GbaK2nGMWnmqzxFUuanfGZie7w7B5Ap30=,tag:yviuqYHqvdfaBrdzICvB6g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
