apiVersion: v1
kind: Secret
metadata:
  name: paperless-ngx
  namespace: paperless
stringData:
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:zKzqOYyIUer+I7ED4Ciss6Ac5SH9F6elN/G8EUR2G2Ep2nF2AmYnSBC3meoFTShcxQN0jHM91VVXLW/g5+9RfvU9I4ZqHqK35YquBKAO5NujafBudjnGadTnWAptv16MVAlRaRAhCUzvHdk6t+gv7cUE7Sn3GH0shB7kUko/LXQp4W7YELeteHElV7fismNej0OHLKI1VIz/LbOBnlzfhQBZ07lgtuEDMbAFjDwsnDIuLn6L0+mAwDWwiRRIeDUhlW1c1xbmuYWnQ5/wk1josdXZm2dsByQOo1aQtSkyszxlciVGmHWpkNW4hsH8BBz/WPlcNvGaEogTbCoC00Uc2rNlT300Q29Nh5LASpumciHVA2XONPlNkbggCvcpArHvmP/eELcjpiOjGjdDCIsUIkdM/M07XfWPP0n0EJ8=,iv:9oVoFO/N1b+tJL3q5PKJWl7g0jv1nc8Gz9OSq3ZOwfo=,tag:dtWF3wR82xhg+EulgVzYTA==,type:str]
sops:
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSTRPeWJ2SkZteC9PeTAw
        YTl6bjBSMjJ6S1lCd3FGZGRTYWZtbGNYbUdFCnJFWTNWekRWV2IvdTR4QU5LYzc2
        bTlKVGE4eDdURGcwbjVla2tUaC82Y00KLS0tIFJTQUhMekVZcXFXaVdYbzZFVS9p
        T2RoZmZENWs5R1dYdW9VVVNnaWdXdjAKqb2ZnF4CgdqzvD29LlvABy4dIQ482BrV
        vCvbL+jjH5dIpvpDp1KcDhBdPnJSn01EXVl5VCppL7UHhJPBc5axIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T00:43:29Z"
  mac: ENC[AES256_GCM,data:o1SKl+SkLKPyrYC+j8PZi68fbx3ijoAH3h7HG6bSWgTuUV2Up7WdBZmVvG51KtOGBjYdfIOM7Qh6r/vAY+WeZS/4BwQb+wy+VqdpVgtVClGP/lvlcgw99tdxoijoVpX29YAqOArl4+lEpe7Yh1FPJJ2MPoaqzv57+nowh82NyHw=,iv:ltfoT+/TlAb6u5+cnKjDLWVopxyrGfW/n94HUI9NwWo=,tag:mwBZ9Ols5W8qqnraiFuXVg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
