---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbird
  namespace: flux-system
spec:
  chart:
    spec:
      chart: netbird
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: netbird
      version: 1.9.x
  install:
    createNamespace: true
  interval: 1m0s
  storageNamespace: netbird
  targetNamespace: netbird
  valuesFrom:
  - kind: ConfigMap
    name: netbird-config-values
