---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: omada-controller
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: omada-controller
    namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: omada-controller
  valuesFrom:
  - kind: ConfigMap
    name: omada-controller-config-values
