---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: piper
  namespace: flux-system
spec:
  chart:
    spec:
      chart: app-template
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.x
  install:
    createNamespace: true
  interval: 30m0s
  targetNamespace: hass
  values:
    global:
      fullnameOverride: piper
    controllers:
      piper:
        containers:
          app:
            image:
              repository: docker.io/rhasspy/wyoming-piper
              tag: "1.5.0"
            args:
              - --voice
              - en_US-lessac-medium
    service:
      app:
        controller: piper
        ports:
          http:
            port: 10200
    persistence:
      data:
        type: emptyDir
        globalMounts:
          - path: /data
            readOnly: false
