---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wakeword
  namespace: wakeword
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    controllers:
      wakeword:
        containers:
          app:
            image:
              repository: docker.io/rhasspy/wyoming-openwakeword
              tag: "1.10.0"
            args:
              - --custom-model-dir
              - /custom
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      app:
        controller: wakeword
        type: LoadBalancer
        ports:
          http:
            port: 10400
    persistence:
      data:
        type: emptyDir
        globalMounts:
          - path: /data
            readOnly: false
      custom:
        type: hostPath
        hostPath: /srv/custom
        hostPathType: DirectoryOrCreate
        globalMounts:
          - readOnly: true
