---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      qbittorrent:
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/qbittorrent
              tag: 4.6.5
            env:
              PUID: 2000
              PGID: 2000
              WEBUI_PORT: 9090
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false

          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.38.0
            env:
              VPN_SERVICE_PROVIDER: mullvad
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              FIREWALL_INPUT_PORTS: 8080
              FIREWALL_OUTBOUND_SUBNETS: 10.96.0.0/12,10.244.0.0/16 # Allow access to k8s subnets
            envFrom:
              - secretRef:
                  name: qbittorrent
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN

          port-forward:
            image:
              repository: ghcr.io/bjw-s/gluetun-qb-port-sync
              tag: v0.0.2@sha256:cb7d25d1a1249d326b9f1cf3afc1c6916b173e6784537245b07044420fd97372
            env:
              GLUETUN_CONTROL_SERVER_HOST: localhost
              GLUETUN_CONTROL_SERVER_PORT: 8000
              QBITTORRENT_HOST: localhost
              QBITTORRENT_WEBUI_PORT: 8080
              CRON_ENABLED: true
              CRON_SCHEDULE: "*/5 * * * *"
              LOG_TIMESTAMP: false

          nzb:
            image:
              repository: ghcr.io/linuxserver/sabnzbd
              tag: 4.3.2
            env:
              PUID: 2000
              PGID: 2000

    service:
      app:
        controller: qbittorrent
        ports:
          qbittorrent:
            port: 9090
          nzb:
            port: 8080

    ingress:
      app:
        hosts:
          - &host
            host: torrent.cjf.sh
            paths:
              - path: /
                service:
                  identifier: qbittorrent
                  port: qbittorrent
          - <<: *host
            host: torrents.cjf.sh
        tls:
          - hosts:
              - torrent.cjf.sh
              - torrents.cjf.sh

    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 2Mi
        globalMounts:
          - path: /config
            readOnly: false
      nzb:
        type: nfs
        server: 10.0.0.70
        path: /var/tank/daijinryuu/nzbget
        advancedMounts:
          qbittorrent:
            nzb:
              - path: /downloads
      torrents:
        type: nfs
        server: 10.0.0.70
        path: /var/tank/daijinryuu/torrents
        advancedMounts:
          qbittorrent:
            app:
              - path: /downloads
