---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      qbittorrent:
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/qbittorrent
              tag: latest
            command:
              - sleep
              - infinity
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false

          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.38.0
            env:
              VPN_SERVICE_PROVIDER: mullvad
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              SERVER_CITIES: Atlanta GA
              FIREWALL_OUTBOUND_SUBNETS: 10.96.0.0/12,10.244.0.0/16 # Allow access to k8s subnets
              DNS_ADDRESS: 10.64.0.1
              WIREGUARD_ADDRESSES:
                valueFrom:
                  secretKeyRef:
                    name: wireguard
                    key: ip-address
              WIREGUARD_PRIVATE_KEY:
                valueFrom:
                  secretKeyRef:
                    name: wireguard
                    key: private-key
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN

    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: 8080

    ingress:
      app:
        hosts:
          - host: torrent.cjf.sh
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - torrent.cjf.sh

    persistence:
      work:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 2Mi
        globalMounts:
          - path: /config
            readOnly: false
      config:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 8Ti
        globalMounts:
          - path: /downloads
            readOnly: false
