---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: flux-system
spec:
  chart:
    spec:
      chart: blackbox-exporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: blackbox-exporter
      version: 11.4.x
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: monitoring
  valuesFrom:
    - kind: ConfigMap
      name: blackbox-exporter-config-values
